/*
 * File: DataAccessClientViewport.ui.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

DataAccessClientViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    id: 'dataAccessClientViewport',
    initComponent: function() {
        this.items = [
            {
                xtype: 'container',
                region: 'west',
                width: 500,
                layout: 'border',
                split: true,
                id: 'inventoryContainer',
                items: [
                    {
                        xtype: 'grid',
                        title: 'Collections',
                        store: 'aCollectionsStore',
                        region: 'north',
                        split: true,
                        height: 150,
                        autoExpandColumn: 2,
                        anchor: '100%,33%',
                        flex: 0.2,
                        ref: '../collectionsGridPanel',
                        id: 'collectionsGridPanel',
                        selModel: new Ext.grid.RowSelectionModel({

                        }),
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'id',
                                header: 'Identifier',
                                sortable: true,
                                width: 60,
                                editable: false
                            },
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'name',
                                header: 'Name',
                                sortable: true,
                                width: 150,
                                editable: false
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Version',
                                sortable: true,
                                editable: false,
                                dataIndex: 'version'
                            }
                        ],
                        tbar: {
                            xtype: 'toolbar',
                            id: 'collectionsToolbar',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Export',
                                    ref: '../../../collectionsGridExportButtonRef',
                                    id: 'collectionsGridExportButton'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Parts',
                        region: 'center',
                        anchor: '100%, 33%',
                        layout: 'fit',
                        flex: 0.4,
                        height: 300,
                        split: true,
                        ref: '../partsPanelRef',
                        id: 'partsPanel',
                        items: [
                            {
                                xtype: 'tabpanel',
                                activeTab: 0,
                                ref: '../../partsTabPanelRef',
                                id: 'partsTabPanel',
                                items: [
                                    {
                                        xtype: 'grid',
                                        title: 'Promoters',
                                        store: 'partStore',
                                        height: 300,
                                        columnLines: true,
                                        stripeRows: true,
                                        autoExpandColumn: 2,
                                        ref: '../../../promotersGridPanelRef',
                                        id: 'promotersGridPanel',
                                        selModel: new Ext.grid.RowSelectionModel({
                                            singleSelect: true
                                        }),
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'id',
                                                header: 'Identifier',
                                                sortable: true,
                                                width: 80,
                                                editable: false
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                header: 'Type',
                                                sortable: true,
                                                width: 100,
                                                dataIndex: 'type'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                header: 'Description',
                                                sortable: true,
                                                width: 175,
                                                dataIndex: 'description'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'grid',
                                        title: '5\' UTR',
                                        store: 'partStore',
                                        height: 300,
                                        columnLines: true,
                                        stripeRows: true,
                                        autoExpandColumn: 2,
                                        ref: '../../../rbsGridPanelRef',
                                        id: 'rbsGridPanel',
                                        selModel: new Ext.grid.RowSelectionModel({
                                            singleSelect: true
                                        }),
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'id',
                                                header: 'Identifier',
                                                sortable: true,
                                                width: 80,
                                                editable: false
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                header: 'Type',
                                                sortable: true,
                                                width: 100,
                                                dataIndex: 'type'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                header: 'Description',
                                                sortable: true,
                                                width: 175,
                                                dataIndex: 'description'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ],
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Show All',
                                    ref: '../../../showAllPartsButtonRef',
                                    id: 'showAllPartsButton'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Export',
                                    ref: '../../../partsGridExportButton',
                                    id: 'partsGridExportButton'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'grid',
                        title: 'Constructs',
                        store: 'constructDisplayStore',
                        height: 300,
                        stripeRows: true,
                        columnLines: true,
                        region: 'south',
                        split: true,
                        anchor: '100%, 33%',
                        flex: 0.4,
                        ref: '../constructsGridPanel',
                        id: 'constructsGridPanel',
                        selModel: new Ext.grid.RowSelectionModel({
                            singleSelect: true
                        }),
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'biofab_id',
                                header: 'Identifier',
                                sortable: true,
                                width: 100,
                                editable: false
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Description',
                                sortable: true,
                                width: 200,
                                dataIndex: 'description',
                                editable: false
                            },
                            {
                                xtype: 'gridcolumn',
                                header: 'Reporter',
                                sortable: true,
                                width: 75,
                                dataIndex: 'reporter',
                                editable: false
                            },
                            {
                                xtype: 'numbercolumn',
                                header: 'Bulk Gene Expression',
                                sortable: true,
                                width: 175,
                                align: 'left',
                                editable: false,
                                dataIndex: 'bulk_gene_expression',
                                format: '0,000'
                            },
                            {
                                xtype: 'numbercolumn',
                                header: 'Standard Deviation',
                                sortable: true,
                                width: 175,
                                align: 'left',
                                editable: false,
                                dataIndex: 'bulk_gene_expression_sd',
                                format: '0,000.0'
                            },
                            {
                                xtype: 'numbercolumn',
                                header: 'Gene Expression per Cell',
                                sortable: true,
                                width: 175,
                                align: 'left',
                                editable: false,
                                dataIndex: 'gene_expression_per_cell',
                                format: '0,000'
                            },
                            {
                                xtype: 'numbercolumn',
                                header: 'Standard Deviation',
                                sortable: true,
                                width: 175,
                                align: 'left',
                                editable: false,
                                dataIndex: 'gene_expression_per_cell_sd',
                                format: '0,000.0'
                            }
                        ],
                        tbar: {
                            xtype: 'toolbar',
                            ref: '../../constructsGridToolbar',
                            id: 'constructsGridToollbar',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Show All',
                                    ref: '../../../showAllConstructsButtonRef',
                                    id: 'showAllConstructsButton'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Export',
                                    ref: '../../../constructsGridExportButton',
                                    id: 'constructsGridExportButton'
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'center',
                split: true,
                ref: 'infoTabPanel',
                id: 'infoTabPanel'
            }
        ];
        DataAccessClientViewportUi.superclass.initComponent.call(this);
    }
});
