/*
 * File: DataAccessClientViewport.ui.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

DataAccessClientViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    id: 'dataAccessClientViewport',
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'west',
                width: 400,
                split: true,
                ref: 'inventoryTabPanel',
                id: 'inventoryTabPanel',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Collections',
                        layout: 'border',
                        items: [
                            {
                                xtype: 'grid',
                                store: 'aCollectionsStore',
                                region: 'center',
                                split: true,
                                height: 200,
                                autoExpandColumn: 2,
                                ref: '../../collectionsGridPanel',
                                id: 'collectionsGridPanel',
                                selModel: new Ext.grid.RowSelectionModel({

                                }),
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'id',
                                        header: 'Identifier',
                                        sortable: true,
                                        width: 60,
                                        editable: false
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'name',
                                        header: 'Name',
                                        sortable: true,
                                        width: 150,
                                        editable: false
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Version',
                                        sortable: true,
                                        editable: false,
                                        dataIndex: 'version'
                                    }
                                ],
                                tbar: {
                                    xtype: 'toolbar',
                                    id: 'collectionsToolbar',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Export',
                                            ref: '../../../../collectionGridExportButton',
                                            id: 'collectionGridExportButton'
                                        }
                                    ]
                                }
                            },
                            {
                                xtype: 'panel',
                                title: 'Collection Description',
                                region: 'south',
                                height: 400,
                                split: true,
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'textarea',
                                        ref: '../../../collectionDescTextArea',
                                        id: 'collectionDescTextArea'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Components',
                        layout: 'border',
                        id: 'componentsPanel',
                        items: [
                            {
                                xtype: 'grid',
                                title: 'Parts',
                                store: 'partStore',
                                height: 300,
                                columnLines: true,
                                stripeRows: true,
                                region: 'north',
                                autoExpandColumn: 2,
                                ref: '../../partsGridPanel',
                                id: 'partsGridPanel',
                                selModel: new Ext.grid.RowSelectionModel({
                                    singleSelect: true
                                }),
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'id',
                                        header: 'Identifier',
                                        sortable: true,
                                        width: 80,
                                        editable: false
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Type',
                                        sortable: true,
                                        width: 100,
                                        dataIndex: 'type'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Description',
                                        sortable: true,
                                        width: 175,
                                        dataIndex: 'description'
                                    }
                                ],
                                tbar: {
                                    xtype: 'toolbar',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Export',
                                            ref: '../../../../partsGridExportButton',
                                            id: 'partsGridExportButton'
                                        }
                                    ]
                                }
                            },
                            {
                                xtype: 'grid',
                                title: 'Constructs',
                                store: 'constructDisplayStore',
                                height: 300,
                                stripeRows: true,
                                columnLines: true,
                                region: 'center',
                                ref: '../../constructsGridPanel',
                                id: 'constructsGridPanel',
                                selModel: new Ext.grid.RowSelectionModel({
                                    singleSelect: true
                                }),
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'id',
                                        header: 'Identifier',
                                        sortable: true,
                                        width: 100,
                                        editable: false
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Description',
                                        sortable: true,
                                        width: 200,
                                        dataIndex: 'description',
                                        editable: false
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        header: 'Mid Log Phase Fluorescence',
                                        sortable: true,
                                        width: 175,
                                        align: 'left',
                                        editable: false,
                                        dataIndex: 'mid_log_phase_fluorescence'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'chassis',
                                        header: 'Strain',
                                        sortable: true,
                                        width: 100,
                                        editable: false
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Media',
                                        sortable: true,
                                        width: 100,
                                        dataIndex: 'media',
                                        editable: false
                                    }
                                ],
                                tbar: {
                                    xtype: 'toolbar',
                                    ref: '../../../constructsGridToolbar',
                                    id: 'constructsGridToollbar',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Export',
                                            ref: '../../../../constructsGridExportButton',
                                            id: 'constructsGridExportButton'
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'center',
                split: true,
                ref: 'infoTabPanel',
                id: 'infoTabPanel'
            }
        ];
        DataAccessClientViewportUi.superclass.initComponent.call(this);
    }
});
