/*
 * File: ConstructPartStore.ui.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

ConstructPartStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        ConstructPartStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'constructPartStore',
            url: '../constructparts',
            autoLoad: true,
            paramNames: {
                format: 'json'
            },
            fields: [
                {
                    name: 'constructID',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'partID',
                    allowBlank: false,
                    type: 'string'
                }
            ]
        }, cfg));
    }
});
new ConstructPartStore();