/*
 * File: ConstructDisplayStore.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.0.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ConstructDisplayStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        ConstructDisplayStore.superclass.constructor.call(this, Ext.apply({
            root: 'constructs',
            url: '../constructs?projectid=1&format=json',
            autoLoad: true,
            storeId: 'constructDisplayStore',
            fields: [
                {
                    name: 'id',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'description',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'mid_log_phase_fluorescence',
                    allowBlank: false,
                    type: 'float',
                    sortDir: 'DESC'
                },
                {
                    name: 'chassis',
                    type: 'string',
                    allowBlank: false
                },
                {
                    name: 'media',
                    type: 'string',
                    allowBlank: false
                }
            ]
        }, cfg));
    }
});
new ConstructDisplayStore();