/*
 * File: ConstructStore.ui.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

ConstructStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        ConstructStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'constructStore',
            root: 'constructs',
            url: '../constructs?collectionid=1&format=json',
            autoLoad: true,
            fields: [
                {
                    name: 'id',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'biofab_id',
                    type: 'string',
                    allowBlank: false
                },
                {
                    name: 'description',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'fluorescence_over_od_mean',
                    allowBlank: false,
                    type: 'float',
                    sortDir: 'DESC'
                },
                {
                    name: 'fluorescence_over_od_sd',
                    allowBlank: false,
                    type: 'float',
                    sortDir: 'DESC'
                },
                {
                    name: 'fluorescence_per_cell_mean',
                    allowBlank: false,
                    type: 'float',
                    sortDir: 'DESC'
                },
                {
                    name: 'fluorescence_per_cell_sd',
                    allowBlank: false,
                    type: 'float',
                    sortDir: 'DESC'
                }
            ]
        }, cfg));
    }
});
new ConstructStore();