/*
 * File: PartStore.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

PartStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        PartStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'partStore',
            //url: '../parts?format=json',
            autoLoad: false,
            fields: [
                {
                    name: 'collectionID',
                    allowBlank: false,
                    type: 'int'
                },
                {
                    name: 'displayID',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'type',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'description',
                    allowBlank: false,
                    type: 'string'
                },
                {
                    name: 'dnaSequence',
                    type: 'string'
                },
                {
                    name: 'measurementType',
                    type: 'string'
                },
                {
                    name: 'measurementValue',
                    type: 'float'
                }
            ]
        }, cfg));
    }
});
new PartStore();