/*
 * File: PilotProjectPanel.ui.js
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file was manually exported.
 */

PartPanelUi = Ext.extend(Ext.Panel, {
    title: 'Part',
    layout: 'border',
    tpl: '',
    closable: true,
    autoScroll: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'DNA Sequence',
                height: 150,
                layout: 'fit',
                ref: 'sequencePanel',
                region: 'north',
                split: true,
                items: [
                    {
                        xtype: 'textarea',
                        ref: '../sequenceTextArea',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Performance',
                layout: 'fit',
                region: 'center',
                //height: 400,
                split: true,
                ref: 'performancePanel',
                html: '<p>\nPerformance data will be available in an upcoming release of the Data Access Client.</p>'
//              items: []
            }
        ];
        PilotProjectPanelUi.superclass.initComponent.call(this);
    }
});
